import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: Request) {
  try {
    const { amount, description, walletAddress } = await request.json();

    if (!amount || !description || !walletAddress) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Supabase can auto-generate the UUID, so we don't need to create it ourselves.
    const payLinkData = {
      // linkId will be generated by the databse
      amount,
      description,
      walletAddress,
      status: "pending",
    };

    // Insert the data into the 'paylinks' table
    const { data, error } = await supabase
      .from("paylinks")
      .insert(payLinkData)
      .select("linkId")
      .single();

    if (error) {
      console.error("Supabase error:", error);
      throw new Error(error.message);
    }

    return NextResponse.json({ linkId: data.linkId }, { status: 200 });
  } catch (error) {
    console.error(error);
    const errorMessage =
      error instanceof Error ? error.message : "Internal Server Error";
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}
